# Generated by Django 4.2.16 on 2024-10-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project_description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='document',
            name='project_title',
            field=models.CharField(default='Untitled Project', max_length=200),
        ),
    ]
