# Generated by Django 4.2.16 on 2024-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_project_description_document_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
