# Generated by Django 4.2.16 on 2024-10-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_image_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image_folder',
        ),
        migrations.RemoveField(
            model_name='document',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_code',
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/source_code/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to='myapp.document')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/presentations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='myapp.document')),
            ],
        ),
    ]
